import turtle
turtle.shape("turtle")
turtle.color("pink")
turtle.width("10")
turtle.penup()
turtle.home()
def thing(that):
    turtle.right(90)
    turtle.forward(that*2)
    turtle.right(90)
    turtle.forward(that*1.5)
    turtle.left(180)
    turtle.pendown()
    turtle.circle(that)
    turtle.penup()
    turtle.forward(that/2)
    turtle.left(90)
    turtle.pendown()
    turtle.forward(that*4)
    turtle.circle(-that,180)
    turtle.forward(4*that)
    turtle.penup()
    turtle.left(90)
    turtle.forward(that/2)
    turtle.pendown()
    turtle.circle(that)
thing(100)
print("LOLZ PIMMEL!")
input("enter to exit")
